######## 회원가입1
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "nickname":"회원이",
  "email":"test2@naver.com",
  "password":"password123",
  "passwordConfirm":"password123"
}

######## 회원가입2
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "nickname":"회원삼",
  "email":"test3@naver.com",
  "password":"password123",
  "passwordConfirm":"password123"
}

######## 중복확인
POST http://localhost:8080/api/auth/nickname
Content-Type: application/json

{
  "nickname":"회원사"
}

######## 중복확인
POST http://localhost:8080/api/auth/email
Content-Type: application/json

{
  "email":"test@naver.com"
}


########로그인1
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email":"test2@naver.com",
  "password":"password123"
}


########로그인2
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email":"test2@naver.com",
  "password":"password12"
}

########회원정보조회
GET http://localhost:8080/api/auth/mypage
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiLtmozsm5DsnbQiLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjI2MjI4MTJ9.FDH0jZjABoIDbmlhqVyufrIvS26RejKvYuGH5ksSFRU
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjMyMjU4MTJ9.N2Vtvj_Wg2fvMgzifTYl_qiw-rotePOtdKCE94YDxgs


########회원정보수정
PUT http://localhost:8080/api/auth/mypage
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiLtmozsm5DsnbQiLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjI2MjI4MTJ9.FDH0jZjABoIDbmlhqVyufrIvS26RejKvYuGH5ksSFRU
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjMyMjU4MTJ9.N2Vtvj_Wg2fvMgzifTYl_qiw-rotePOtdKCE94YDxgs
Content-Type: application/json

{
  "nickname":"회원일이",
  "passwordConfirm":"password12",
  "newPassword":"password12"
}