###회원가입1############
POST http://localhost:8080/api/member/signup
Content-Type: application/json

{
  "nickname":"kiyeon",
  "password":"1234",
  "passwordConfirm":"1234"
}

###회원가입2############
POST http://localhost:8080/api/member/signup
Content-Type: application/json

{
  "nickname":"seonghee",
  "password":"1234",
  "passwordConfirm":"1234"
}


###로그인1##################
POST http://localhost:8080/api/member/login
Content-Type: application/json

{
  "nickname":"kiyeon",
  "password":"1234"
}

###로그인2##################
POST http://localhost:8080/api/member/login
Content-Type: application/json

{
  "nickname":"seonghee",
  "password":"1234"
}

###멤버1 게시글 작성##############

POST http://localhost:8080/api/auth/post
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjE5MzIzODR9.IWwc6BGTFZC-zqcOQP7msaedvHAiQgqywUlakOEXTnc
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI1MzUzODR9.oZad_PAoCegZkZCkWZP49BVYzbUVOqVus2k2GDma2Mg
Content-Type: application/json

{
  "title":"게시글 test1",
  "content":"회원1의 게시글 내용 1"
}

###멤버1 게시글 작성##############

POST http://localhost:8080/api/auth/post
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjE5MzIzODR9.IWwc6BGTFZC-zqcOQP7msaedvHAiQgqywUlakOEXTnc
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI1MzUzODR9.oZad_PAoCegZkZCkWZP49BVYzbUVOqVus2k2GDma2Mg
Content-Type: application/json

{
  "title":"게시글 test2",
  "content":"회원1의 게시글 내용 1"
}

###게시글 확인###########
GET http://localhost:8080/api/post



###멤버1 댓글 달기##############

POST http://localhost:8080/api/auth/comment
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjE5MzIzODR9.IWwc6BGTFZC-zqcOQP7msaedvHAiQgqywUlakOEXTnc
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI1MzUzODR9.oZad_PAoCegZkZCkWZP49BVYzbUVOqVus2k2GDma2Mg
Content-Type: application/json

{
"postId":"1",
"content":"댓글 작성자: 회원1/ 게시글 1의 댓글 1"

}

###댓글 확인##################
GET http://localhost:8080/api/comment/1

###멤버2 댓글 달기##############

POST http://localhost:8080/api/auth/comment
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MTkzMjQwNH0.BlLRyupxFMV3mdfCcFoMtDCyUfozz_b4GFLqnZPvuwg
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI1MzU0MDR9.No9yxrs0C24FjViLHGY0rVeLCspMrT3K2aELwkpDm7A
Content-Type: application/json

{
  "postId":"2",
  "content":"댓글 작성자: 회원2/ 게시글 2의 댓글 2"

}

####회원 1의 자기 댓글 업데이트##############
#PUT http://localhost:8080/api/auth/comment/1
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjE4Njg0Njl9.httygt3hNuBcDqND45Yyj6xl4UybUcE9ZUIHgpoIx6o
#Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI0NzE0Njl9.-rwBLfZV5f7k5_Ge6SZeSvoDNVrsQ4r__-wO2YQpOWI
#Content-Type: application/json
#
#{
#  "postId":"1",
#  "content":"댓글 수정자: 회원1/ 게시글 1의 댓글 1의 본인 수정버전"
#}




###회원2 대댓글 달기1#################
POST http://localhost:8080/api/auth/recomment
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MTkzMjQwNH0.BlLRyupxFMV3mdfCcFoMtDCyUfozz_b4GFLqnZPvuwg
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI1MzU0MDR9.No9yxrs0C24FjViLHGY0rVeLCspMrT3K2aELwkpDm7A
Content-Type: application/json

{
  "postId":"1",
  "commentId":"1",
  "content":"대댓글 작성자: 회원2/ 게시글 1의 댓글 1의 대댓글 1"
}

###회원2 대댓글 달기2#################
POST http://localhost:8080/api/auth/recomment
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MTkzMjQwNH0.BlLRyupxFMV3mdfCcFoMtDCyUfozz_b4GFLqnZPvuwg
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI1MzU0MDR9.No9yxrs0C24FjViLHGY0rVeLCspMrT3K2aELwkpDm7A
Content-Type: application/json

{
  "postId":"1",
  "commentId":"1",
  "content":"대댓글 작성자: 회원2/ 게시글 1의 댓글 1의 대댓글 2"
}

###댓글1의 대댓글 확인#################
GET http://localhost:8080/api/recomment/1


####대댓글 수정 확인#############
#PUT http://localhost:8080/api/auth/recomment/1
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MTg2NjU3OX0.e3pd6uGMQozEw0y2Ed3jzEhdMjpLIJ8norsaBtb8Zdo
#Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI0Njk1Nzl9.gmFYKEu_cmPZKIjNLZq3MmKM3DYk_9_3_IMEZcMoDHY
#Content-Type: application/json
#
#{
#
#  "postId":"1",
#  "commentId":"2",
#  "content":"대댓글 수정자: 회원2/ 게시글 1의 댓글 1의 대댓글 1의 수정"
#
#}

#### 회원1 post1에 좋아요
POST http://localhost:8080/api/auth/like/post/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjE5MzIzODR9.IWwc6BGTFZC-zqcOQP7msaedvHAiQgqywUlakOEXTnc
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI1MzUzODR9.oZad_PAoCegZkZCkWZP49BVYzbUVOqVus2k2GDma2Mg

##### 회원2 post2에 좋아요
POST http://localhost:8080/api/auth/like/post/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MTkzMjQwNH0.BlLRyupxFMV3mdfCcFoMtDCyUfozz_b4GFLqnZPvuwg
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI1MzU0MDR9.No9yxrs0C24FjViLHGY0rVeLCspMrT3K2aELwkpDm7A

#### 회원1 post2에 좋아요
POST http://localhost:8080/api/auth/like/post/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjE5MzIzODR9.IWwc6BGTFZC-zqcOQP7msaedvHAiQgqywUlakOEXTnc
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI1MzUzODR9.oZad_PAoCegZkZCkWZP49BVYzbUVOqVus2k2GDma2Mg

#### 회원1 post2에 좋아요 취소
POST http://localhost:8080/api/auth/like/post/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjE5MzIzODR9.IWwc6BGTFZC-zqcOQP7msaedvHAiQgqywUlakOEXTnc
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI1MzUzODR9.oZad_PAoCegZkZCkWZP49BVYzbUVOqVus2k2GDma2Mg

###  회원1 댓글1에 좋아요
POST http://localhost:8080/api/auth/like/comment/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjE5MzIzODR9.IWwc6BGTFZC-zqcOQP7msaedvHAiQgqywUlakOEXTnc
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI1MzUzODR9.oZad_PAoCegZkZCkWZP49BVYzbUVOqVus2k2GDma2Mg

#### 회원1 댓글2에 좋아요
POST http://localhost:8080/api/auth/like/comment/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjE5MzIzODR9.IWwc6BGTFZC-zqcOQP7msaedvHAiQgqywUlakOEXTnc
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI1MzUzODR9.oZad_PAoCegZkZCkWZP49BVYzbUVOqVus2k2GDma2Mg

### 회원2 댓글 2에 좋아요
POST http://localhost:8080/api/auth/like/comment/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MTkzMjQwNH0.BlLRyupxFMV3mdfCcFoMtDCyUfozz_b4GFLqnZPvuwg
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI1MzU0MDR9.No9yxrs0C24FjViLHGY0rVeLCspMrT3K2aELwkpDm7A

#### 회원2 댓글 2에 좋아요 취소
POST http://localhost:8080/api/auth/like/comment/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MTkzMjQwNH0.BlLRyupxFMV3mdfCcFoMtDCyUfozz_b4GFLqnZPvuwg
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI1MzU0MDR9.No9yxrs0C24FjViLHGY0rVeLCspMrT3K2aELwkpDm7A

#### 회원2 대댓글1에 좋아요
POST http://localhost:8080/api/auth/like/recomment/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MTkzMjQwNH0.BlLRyupxFMV3mdfCcFoMtDCyUfozz_b4GFLqnZPvuwg
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI1MzU0MDR9.No9yxrs0C24FjViLHGY0rVeLCspMrT3K2aELwkpDm7A

#### 회원2 대댓글2에 좋아요
POST http://localhost:8080/api/auth/like/recomment/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MTkzMjQwNH0.BlLRyupxFMV3mdfCcFoMtDCyUfozz_b4GFLqnZPvuwg
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI1MzU0MDR9.No9yxrs0C24FjViLHGY0rVeLCspMrT3K2aELwkpDm7A

#### 회원2 대댓글2에 좋아요 취소
POST http://localhost:8080/api/auth/like/recomment/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MTkzMjQwNH0.BlLRyupxFMV3mdfCcFoMtDCyUfozz_b4GFLqnZPvuwg
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI1MzU0MDR9.No9yxrs0C24FjViLHGY0rVeLCspMrT3K2aELwkpDm7A

### 회원1 대댓글2에 좋아요
POST http://localhost:8080/api/auth/like/recomment/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjE5MzIzODR9.IWwc6BGTFZC-zqcOQP7msaedvHAiQgqywUlakOEXTnc
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI1MzUzODR9.oZad_PAoCegZkZCkWZP49BVYzbUVOqVus2k2GDma2Mg

### 회원1


####대댓글 2번 삭제 확인#############
#DELETE http://localhost:8080/api/auth/recomment/2
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MTg2NjU3OX0.e3pd6uGMQozEw0y2Ed3jzEhdMjpLIJ8norsaBtb8Zdo
#Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI0Njk1Nzl9.gmFYKEu_cmPZKIjNLZq3MmKM3DYk_9_3_IMEZcMoDHY
